### ISSUE TITLE
Improve the output of the scientific "e" notation

### ISSUE THREAD

**Issue by dbatten5** [josephcslater/array_to_latex#15]
Currently if the `mathform=False` argument is added to the `to_ltx` method, then the output has the form `-1.2e-01` which renders as
```math
-1.2e-01
```
From reading some latex q&a online it seems like the `\mathrm{e}{-01}` form is preferred:
```math
-1.2\mathrm{e}{-01}
```
Would it be possible to update this package with the above? I'm happy to implement it myself and raise a PR if that helps

Thanks!

**Comment by josephcslater** [comment]
Please do. I will take all the help I can get.

**Comment by dbatten5** [comment]
Hi, I've added a PR if you'd like to review when convenient

**Comment by josephcslater** [comment]
Does the current version satisfy this? There was a major update, and I think this was included (I didn't dig into the code).

**Comment by dbatten5** [comment]
Seems like it wasn't included https://github.com/josephcslater/array_to_latex/blob/master/array_to_latex/__init__.py#L391-L393

**Comment by josephcslater** [comment]
Instead of using 'e', the code uses `10^n`, which is more typical to typesetting. Given the substantive changes, and this current behavior being the most common desired outcome, I think the best path is to have another flag, with a good name, to leave the default behavior as it is, but create the alternative as desired by the user. That's a bit more extensive, but I'd certainly support such a pull request.

**Comment by dbatten5** [comment]
Yeah the code uses $1 \times 10^{-03}$ notation by default, but if the `mathform` flag is set to False then it'll be rendered as $1e-03$. Given that this otuput doesn't look so great when rendered, this issue was just about improving the current behaviour so I don't think it needs a new flag. The initial PR I did does just that so I could reopen that if you like?

**Comment by josephcslater** [comment]
Will it merge appropriately? There was a substantial update last week.  Certainly a worthwhile addition. I just haven’t tested it with the other updates. I want to be cautious and ensure it’s working before releasing.  I’m old- wisdom the hard way. Sent from my iPhone. I blame Steve Jobs and autocorrect for any errors. On Mar 26, 2023, at 12:10 PM, dbatten5 ***@***.***> wrote:﻿
Yeah the code uses $1 \times 10^{03}$ notation by default, but if the mathform flag is set to False then it'll be rendered as $1e03$. Given that this otuput doesn't look so great when rendered, this issue was just about improving the current behaviour so I don't think it needs a new flag. The initial PR I did does just that so I could reopen that if you like?

**Comment by dbatten5** [comment]
Yeah understandable - looks like the changes recently merged were on a separate bit of the file so should be fine

**Comment by josephcslater** [comment]
Ok.  If you reopen. I’ll pull. Sent from my iPhone. I blame Steve Jobs and autocorrect for any errors. On Mar 26, 2023, at 12:30 PM, dbatten5 ***@***.***> wrote:﻿
Yeah understandable - looks like the changes recently merged were on a separate bit of the file so should be fine

**Comment by josephcslater** [comment]
If you wish, update the readme ( short list top, long list bottom) and increment version number. That will set it up for a new release. Sent from my iPhone. I blame Steve Jobs and autocorrect for any errors. On Mar 26, 2023, at 12:30 PM, dbatten5 ***@***.***> wrote:﻿
Yeah understandable - looks like the changes recently merged were on a separate bit of the file so should be fine

**Comment by dbatten5** [comment]
Done https://github.com/josephcslater/array_to_latex/pull/18
